### ISSUE TITLE
Ivory cli tests don't appear to be working from clean check-out.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/ivory#686]
Something changed about what it pulls down from cdh mirror? Or it is something local to my env - but that is pretty minimal jdk install - so thought this should just work.

```
+ ./ivory-cli/src/test/bin/../../../../bin/hadoop-dev ./ivory-cli/src/test/bin/../../../../target/ivory-cli/lib/ivory.jar com.ambiata.ivory.cli.main ingest -i sparse:delimited:psv=./ivory-cli/src/test/bin/tests/window/../../../../../../target/regression//input
log4j:WARN No appenders could be found for logger (com.ambiata.com.amazonaws.internal.config.InternalConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
*** WARNING: Codec has been disabled - do NOT do this in production! ***
================================================================================

Ivory:
  Version:             1.0.0-cdh5-20150913013314-53b2762
  Path:                /tmp/ivory-20150913113752-10670
  Planning Strategy:   pessimistic

Hadoop:
  Version:             2.2.0-cdh5.0.0-beta-2

JVM:
  Version:             1.7.0_79
  Maximum Memory:      932184064

================================================================================

============================================================
Error[java.lang.NoClassDefFoundError] org/apache/hadoop/mapreduce/Job
------------------------------------------------------------
    java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/Job
        at com.ambiata.ivory.operation.ingestion.IngestJob$.run(mr.scala:33)
        at com.ambiata.ivory.operation.ingestion.FactImporter$$anonfun$runJob$3$$anonfun$apply$10.apply(FactImporter.scala:48)
        at com.ambiata.ivory.operation.ingestion.FactImporter$$anonfun$runJob$3$$anonfun$apply$10.apply(FactImporter.scala:46)
        at com.ambiata.mundane.control.RIO$$anonfun$flatMap$1$$anonfun$apply$6.apply(RIO.scala:56)
        at com.ambiata.mundane.control.RIO$$anonfun$flatMap$1$$anonfun$apply$6.apply(RIO.scala:56)
```

**Comment by raronson** [comment]
I get this when i have `HADOOP` or `HADOOP_HOME` env vars set

**Comment by tmcgilchrist** [comment]
They're working on my naive freshly checked out version of ivory and I'm rather sure I don't have any `HADOOP` setup at all.
